---
name: "ci"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Pak Name
        id: pak-name
        run: |
          echo "PAK_NAME=$(jq -r .label config.json)" >> $GITHUB_OUTPUT

      - name: Create Release zip
        run: |
          mkdir -p dist
          git archive --format=zip --output "dist/${{ steps.pak-name.outputs.PAK_NAME }}.zip" HEAD

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.1.0
        with:
          subject-path: "dist/${{ steps.pak-name.outputs.PAK_NAME }}.zip"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
