---
name: "tagged-release"

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*"

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  tagged-release:
    name: tagged-release
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Create release
        run: make clean build release

      - name: Get Pak Name
        id: pak-name
        run: |
          echo "PAK_NAME=$(jq -r .label config.json)" >> $GITHUB_OUTPUT

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.1.0
        with:
          subject-path: "dist/${{ steps.pak-name.outputs.PAK_NAME }}.pak.zip"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          make_latest: "true"
